version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - .:/app
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/
      && ng serve --host=0.0.0.0 --aot"
